spring:

  datasource:
    url: jdbc:mysql://13.125.198.11:3306/gang
    username: gang
    password: gang1200
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    generate-ddl: false
logging:
  level:
    org.hibernate.type: trace
    org.springframework: INFO
    org.springframework.web: DEBUG
server:
  port: 80