
spring:
  h2:
    console:
      enabled=true:
  datasource:
    url: jdbc:h2:tcp://localhost/~/gang
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: true
    generate-ddl: false
