INSERT INTO category VALUES(1,'관광명소');
INSERT INTO category VALUES(2,'음식점');
INSERT INTO category VALUES(3,'카페');
INSERT INTO province VALUES(1,'경기도', 'src/province/경기도.png');
INSERT INTO province VALUES(2,'강원도', 'src/province/강원도.png');
INSERT INTO province VALUES(3,'충청남도', 'src/province/충청남도.png');
INSERT INTO province VALUES(4,'충청북도', 'src/province/충청북도.png');
INSERT INTO province VALUES(5,'전라남도', 'src/province/전라남도.png');
INSERT INTO province VALUES(6,'전라북도', 'src/province/전라북도.png');
INSERT INTO province VALUES(7,'경상남도', 'src/province/경상남도.png');
INSERT INTO province VALUES(8,'경상북도', 'src/province/경상북도.png');
INSERT INTO province VALUES(9,'인천광역시', 'src/province/인천광역시.png');
INSERT INTO province VALUES(10,'대전광역시', 'src/province/대전광역시.png');
INSERT INTO province VALUES(11,'대구광역시', 'src/province/대구광역시.png');
INSERT INTO province VALUES(12,'부산광역시', 'src/province/부산광역시.png');
INSERT INTO province VALUES(13,'울산광역시', 'src/province/울산광역시.png');
INSERT INTO province VALUES(14,'광주광역시', 'src/province/광주광역시.png');
INSERT INTO province VALUES(15,'세종특별시', 'src/province/세종특별시.png');
INSERT INTO city VALUES(1,'src/city/가평군.png','가평군',1);
INSERT INTO city VALUES(2,'src/city/광명시.png','광명시',1);
INSERT INTO city VALUES(3,'src/city/연천군.png','연천군',1);
INSERT INTO city VALUES(4,'src/city/남양주시.png','남양주시',1);
INSERT INTO city VALUES(5,'src/city/파주시.png','파주시',1);
INSERT INTO city VALUES(6,'src/city/동두천시.png','동두천시',1);
INSERT INTO city VALUES(7,'src/city/화성시.png','화성시',1);
INSERT INTO city VALUES(8,'src/city/양평군.png','양평군',1);
INSERT INTO city VALUES(9,'src/city/고양시.png','고양시',1);
INSERT INTO city VALUES(10,'src/city/평택시.png','평택시',1);
INSERT INTO city VALUES(11,'src/city/수원시.png','수원시',1);
INSERT INTO city VALUES(12,'src/city/안양시.png','안양시',1);
INSERT INTO city VALUES(13,'src/city/오산시.png','오산시',1);
INSERT INTO city VALUES(14,'src/city/의정부시.png','의정부시',1);
INSERT INTO city VALUES(15,'src/city/강릉시.png','강릉시',2);
INSERT INTO city VALUES(16,'src/city/춘천시.png','춘천시',2);
INSERT INTO city VALUES(17,'src/city/정선군.png','정선군',2);
INSERT INTO city VALUES(18,'src/city/삼척시.png','삼척시',2);
INSERT INTO city VALUES(19,'src/city/태백시.png','태백시',2);
INSERT INTO city VALUES(20,'src/city/동해시.png','동해시',2);
INSERT INTO city VALUES(21,'src/city/원주시.png','원주시',2);
INSERT INTO city VALUES(22,'src/city/횡성군.png','횡성군',2);
INSERT INTO city VALUES(23,'src/city/철원군.png','철원군',2);
INSERT INTO city VALUES(24,'src/city/평창군.png','평창군',2);
INSERT INTO city VALUES(25,'src/city/영월군.png','영월군',2);
INSERT INTO city VALUES(26,'src/city/논산시.png','논산시',3);
INSERT INTO city VALUES(27,'src/city/계룡시.png','계룡시',3);
INSERT INTO city VALUES(28,'src/city/공주시.png','공주시',3);
INSERT INTO city VALUES(29,'src/city/홍성군.png','홍성군',3);
INSERT INTO city VALUES(30,'src/city/보령시.png','보령시',3);
INSERT INTO city VALUES(31,'src/city/아산시.png','아산시',3);
INSERT INTO city VALUES(32,'src/city/서천군.png','서천군',3);
INSERT INTO city VALUES(33,'src/city/천안시.png','천안시',3);
INSERT INTO city VALUES(34,'src/city/예산군.png','예산군',3);
INSERT INTO city VALUES(35,'src/city/영동군.png','영동군',4);
INSERT INTO city VALUES(36,'src/city/단양군.png','단양군',4);
INSERT INTO city VALUES(37,'src/city/청주시.png','청주시',4);
INSERT INTO city VALUES(38,'src/city/충주시.png','충주시',4);
INSERT INTO city VALUES(39,'src/city/제천시.png','제천시',4);
INSERT INTO city VALUES(40,'src/city/증평군.png','증평군',4);
INSERT INTO city VALUES(41,'src/city/옥천군.png','옥천군',4);
INSERT INTO city VALUES(42,'src/city/음성군.png','음성군',4);
INSERT INTO city VALUES(43,'src/city/곡성군.png','곡성군',5);
INSERT INTO city VALUES(44,'src/city/광양시.png','광양시',5);
INSERT INTO city VALUES(45,'src/city/순천시.png','순천시',5);
INSERT INTO city VALUES(46,'src/city/나주시.png','나주시',5);
INSERT INTO city VALUES(47,'src/city/화순군.png','화순군',5);
INSERT INTO city VALUES(48,'src/city/보성군.png','보성군',5);
INSERT INTO city VALUES(49,'src/city/목포시.png','목포시',5);
INSERT INTO city VALUES(50,'src/city/무안군.png','무안군',5);
INSERT INTO city VALUES(51,'src/city/장성군.png','장성군',5);
INSERT INTO city VALUES(52,'src/city/함평군.png','함평군',5);
INSERT INTO city VALUES(53,'src/city/여수시.png','여수시',5);
INSERT INTO city VALUES(54,'src/city/군산시.png','군산시',6);
INSERT INTO city VALUES(55,'src/city/김제시.png','김제시',6);
INSERT INTO city VALUES(56,'src/city/익산시.png','익산시',6);
INSERT INTO city VALUES(57,'src/city/전주시.png','전주시',6);
INSERT INTO city VALUES(58,'src/city/정읍시.png','정읍시',6);
INSERT INTO city VALUES(59,'src/city/완주군.png','완주군',6);
INSERT INTO city VALUES(60,'src/city/임실군.png','임실군',6);
INSERT INTO city VALUES(61,'src/city/남원시.png','남원시',6);
INSERT INTO city VALUES(62,'src/city/창원시.png','창원시',7);
INSERT INTO city VALUES(63,'src/city/밀양시.png','밀양시',7);
INSERT INTO city VALUES(64,'src/city/진주시.png','진주시',7);
INSERT INTO city VALUES(65,'src/city/하동군.png','하동군',7);
INSERT INTO city VALUES(66,'src/city/김해시.png','김해시',7);
INSERT INTO city VALUES(67,'src/city/사천시.png','사천시',7);
INSERT INTO city VALUES(68,'src/city/양산시.png','양산시',7);
INSERT INTO city VALUES(69,'src/city/함안군.png','함안군',7);
INSERT INTO city VALUES(70,'src/city/영덕군.png','영덕군',8);
INSERT INTO city VALUES(71,'src/city/구미시.png','구미시',8);
INSERT INTO city VALUES(72,'src/city/예천군.png','예천군',8);
INSERT INTO city VALUES(73,'src/city/경주시.png','경주시',8);
INSERT INTO city VALUES(74,'src/city/경산시.png','경산시',8);
INSERT INTO city VALUES(75,'src/city/청도군.png','청도군',8);
INSERT INTO city VALUES(76,'src/city/봉화군.png','봉화군',8);
INSERT INTO city VALUES(77,'src/city/영천시.png','영천시',8);
INSERT INTO city VALUES(78,'src/city/상주시.png','상주시',8);
INSERT INTO city VALUES(79,'src/city/군위군.png','군위군',8);
INSERT INTO city VALUES(80,'src/city/영주시.png','영주시',8);
INSERT INTO city VALUES(81,'src/city/포항시.png','포항시',8);
INSERT INTO city VALUES(82,'src/city/의성군.png','의성군',8);
INSERT INTO city VALUES(83,'src/city/문경시.png','문경시',8);
INSERT INTO city VALUES(84,'src/city/칠곡군.png','칠곡군',8);
INSERT INTO city VALUES(85,'src/city/안동시.png','안동시',8);
INSERT INTO city VALUES(86,'src/city/김천시.png','김천시',8);
INSERT INTO city VALUES(87,'src/city/인천광역시.png','인천',9);
INSERT INTO city VALUES(88,'src/city/대전광역시.png','대전',10);
INSERT INTO city VALUES(89,'src/city/대구광역시.png','대구',11);
INSERT INTO city VALUES(90,'src/city/부산광역시.png','부산',12);
INSERT INTO city VALUES(91,'src/city/울산광역시.png','울산',13);
INSERT INTO city VALUES(92,'src/city/광주광역시.png','광주',14);
INSERT INTO city VALUES(93,'src/city/세종특별시.png','세종',15);
INSERT INTO station VALUES(1,'가평역',1);
INSERT INTO station VALUES(2,'대성리역',1);
INSERT INTO station VALUES(3,'청평역',1);
INSERT INTO station VALUES(4,'광명역',2);
INSERT INTO station VALUES(5,'대광리역',3);
INSERT INTO station VALUES(6,'한탄강역',3);
INSERT INTO station VALUES(7,'초성리역',3);
INSERT INTO station VALUES(8,'전곡역',3);
INSERT INTO station VALUES(9,'신망리역',3);
INSERT INTO station VALUES(10,'신탄리역',3);
INSERT INTO station VALUES(11,'연천역',3);
INSERT INTO station VALUES(12,'덕소역',4);
INSERT INTO station VALUES(13,'마석역',4);
INSERT INTO station VALUES(14,'평내호평역',4);
INSERT INTO station VALUES(15,'퇴계원역',4);
INSERT INTO station VALUES(16,'사릉역',4);
INSERT INTO station VALUES(17,'도라산역',5);
INSERT INTO station VALUES(18,'문산역',5);
INSERT INTO station VALUES(19,'운천역',5);
INSERT INTO station VALUES(20,'임진강역',5);
INSERT INTO station VALUES(21,'동두천역',6);
INSERT INTO station VALUES(22,'소요산역',6);
INSERT INTO station VALUES(23,'동탄역',7);
INSERT INTO station VALUES(24,'매곡역',8);
INSERT INTO station VALUES(25,'지평역',8);
INSERT INTO station VALUES(26,'삼산역',8);
INSERT INTO station VALUES(27,'석불역',8);
INSERT INTO station VALUES(28,'양동역',8);
INSERT INTO station VALUES(29,'양평역',8);
INSERT INTO station VALUES(30,'용문역',8);
INSERT INTO station VALUES(31,'일신역',8);
INSERT INTO station VALUES(32,'행신역',9);
INSERT INTO station VALUES(33,'평택역',10);
INSERT INTO station VALUES(34,'평택지제역',10);
INSERT INTO station VALUES(35,'서정리역',10);
INSERT INTO station VALUES(36,'수원역',11);
INSERT INTO station VALUES(37,'안양역',12);
INSERT INTO station VALUES(38,'오산역',13);
INSERT INTO station VALUES(39,'의정부역',14);
INSERT INTO station VALUES(40,'강릉역',15);
INSERT INTO station VALUES(41,'정동진역',15);
INSERT INTO station VALUES(42,'안인역',15);
INSERT INTO station VALUES(43,'강촌역',16);
INSERT INTO station VALUES(44,'김유정역',16);
INSERT INTO station VALUES(45,'남춘천역',16);
INSERT INTO station VALUES(46,'백양리역',16);
INSERT INTO station VALUES(47,'춘천역',16);
INSERT INTO station VALUES(48,'고한역',17);
INSERT INTO station VALUES(49,'나전역',17);
INSERT INTO station VALUES(50,'민둥산역',17);
INSERT INTO station VALUES(51,'별어곡역',17);
INSERT INTO station VALUES(52,'정선역',17);
INSERT INTO station VALUES(53,'사북역',17);
INSERT INTO station VALUES(54,'선평역',17);
INSERT INTO station VALUES(55,'아우라지역',17);
INSERT INTO station VALUES(56,'예미역',17);
INSERT INTO station VALUES(57,'도계역',18);
INSERT INTO station VALUES(58,'삼척해변역',18);
INSERT INTO station VALUES(59,'신기역',18);
INSERT INTO station VALUES(60,'동백산역',19);
INSERT INTO station VALUES(61,'태백역',19);
INSERT INTO station VALUES(62,'철암역',19);
INSERT INTO station VALUES(63,'동해역',20);
INSERT INTO station VALUES(64,'망상해변역',20);
INSERT INTO station VALUES(65,'묵호역',20);
INSERT INTO station VALUES(66,'추암역',20);
INSERT INTO station VALUES(67,'동화역',21);
INSERT INTO station VALUES(68,'만종역',21);
INSERT INTO station VALUES(69,'반곡역',21);
INSERT INTO station VALUES(70,'서원주역',21);
INSERT INTO station VALUES(71,'원주역',21);
INSERT INTO station VALUES(72,'둔내역',22);
INSERT INTO station VALUES(73,'횡성역',22);
INSERT INTO station VALUES(74,'백마고지역',23);
INSERT INTO station VALUES(75,'평창역',24);
INSERT INTO station VALUES(76,'진부오대산역',24);
INSERT INTO station VALUES(77,'영월역',25);
INSERT INTO station VALUES(78,' 쌍룡역',25);
INSERT INTO station VALUES(79,'강경역',26);
INSERT INTO station VALUES(80,'논산역',26);
INSERT INTO station VALUES(81,'연산역',26);
INSERT INTO station VALUES(82,'계룡역',27);
INSERT INTO station VALUES(83,'공주역',28);
INSERT INTO station VALUES(84,'광천역',29);
INSERT INTO station VALUES(85,'홍성역',29);
INSERT INTO station VALUES(86,'대천역',30);
INSERT INTO station VALUES(87,'청소역',30);
INSERT INTO station VALUES(88,'웅천역',30);
INSERT INTO station VALUES(89,'도고온천역',31);
INSERT INTO station VALUES(90,'천안아산역',31);
INSERT INTO station VALUES(91,'신창역',31);
INSERT INTO station VALUES(92,'아산역',31);
INSERT INTO station VALUES(93,'온양온천역',31);
INSERT INTO station VALUES(94,'판교역',32);
INSERT INTO station VALUES(95,'서천역',32);
INSERT INTO station VALUES(96,'장항역',32);
INSERT INTO station VALUES(97,'천안역',33);
INSERT INTO station VALUES(98,'성환역',33);
INSERT INTO station VALUES(99,'삽교역',34);
INSERT INTO station VALUES(100,'신례원역',34);
INSERT INTO station VALUES(101,'예산역',34);
INSERT INTO station VALUES(102,'각계역',35);
INSERT INTO station VALUES(103,'추풍령역',35);
INSERT INTO station VALUES(104,'심천역',35);
INSERT INTO station VALUES(105,'영동역',35);
INSERT INTO station VALUES(106,' 황간역',35);
INSERT INTO station VALUES(107,'단양역',36);
INSERT INTO station VALUES(108,'청주역',37);
INSERT INTO station VALUES(109,'청주공항역',37);
INSERT INTO station VALUES(110,'오근장역',37);
INSERT INTO station VALUES(111,'오송역',37);
INSERT INTO station VALUES(112,'충주역',38);
INSERT INTO station VALUES(113,'주덕역',38);
INSERT INTO station VALUES(114,'삼탄역',38);
INSERT INTO station VALUES(115,'제천역',39);
INSERT INTO station VALUES(116,'입석리역',39);
INSERT INTO station VALUES(117,'증평역',40);
INSERT INTO station VALUES(118,'지탄역',41);
INSERT INTO station VALUES(119,'옥천역',41);
INSERT INTO station VALUES(120,'이원역',41);
INSERT INTO station VALUES(121,'음성역',42);
INSERT INTO station VALUES(122,'곡성역',43);
INSERT INTO station VALUES(123,'광양역',44);
INSERT INTO station VALUES(124,'진상역',44);
INSERT INTO station VALUES(125,'구례구역',45);
INSERT INTO station VALUES(126,'순천역',45);
INSERT INTO station VALUES(127,'나주역',46);
INSERT INTO station VALUES(128,'다시역',46);
INSERT INTO station VALUES(129,'능주역',47);
INSERT INTO station VALUES(130,'화순역',47);
INSERT INTO station VALUES(131,'이양역',47);
INSERT INTO station VALUES(132,'명봉역',48);
INSERT INTO station VALUES(133,'벌교역',48);
INSERT INTO station VALUES(134,'보성역',48);
INSERT INTO station VALUES(135,'조성역',48);
INSERT INTO station VALUES(136,'예당역',48);
INSERT INTO station VALUES(137,' 득량역',48);
INSERT INTO station VALUES(138,'목포역',49);
INSERT INTO station VALUES(139,'임성리역',49);
INSERT INTO station VALUES(140,'몽탄역',50);
INSERT INTO station VALUES(141,'무안역',50);
INSERT INTO station VALUES(142,'일로역',50);
INSERT INTO station VALUES(143,'백양사역',51);
INSERT INTO station VALUES(144,'장성역',51);
INSERT INTO station VALUES(145,'함평역',52);
INSERT INTO station VALUES(146,'여수EXPO역',53);
INSERT INTO station VALUES(147,'여천역',53);
INSERT INTO station VALUES(148,'군산역',54);
INSERT INTO station VALUES(149,'대야역',54);
INSERT INTO station VALUES(150,'김제역',55);
INSERT INTO station VALUES(151,'함열역',56);
INSERT INTO station VALUES(152,'익산역',56);
INSERT INTO station VALUES(153,'전주역',57);
INSERT INTO station VALUES(154,'정읍역',58);
INSERT INTO station VALUES(155,'신태인역',58);
INSERT INTO station VALUES(156,'삼례역',59);
INSERT INTO station VALUES(157,'오수역',60);
INSERT INTO station VALUES(158,'임실역',60);
INSERT INTO station VALUES(159,'남원역',61);
INSERT INTO station VALUES(160,'마산역',62);
INSERT INTO station VALUES(161,'창원역',62);
INSERT INTO station VALUES(162,'창원중앙역',62);
INSERT INTO station VALUES(163,'중리역',62);
INSERT INTO station VALUES(164,'밀양역',63);
INSERT INTO station VALUES(165,'삼랑진역',63);
INSERT INTO station VALUES(166,'상동역',63);
INSERT INTO station VALUES(167,'반성역',64);
INSERT INTO station VALUES(168,'진주역',64);
INSERT INTO station VALUES(169,'북천역',65);
INSERT INTO station VALUES(170,'하동역',65);
INSERT INTO station VALUES(171,'횡천역',65);
INSERT INTO station VALUES(172,'한림정역',66);
INSERT INTO station VALUES(173,'진례역',66);
INSERT INTO station VALUES(174,'진영역',66);
INSERT INTO station VALUES(175,'완사역',67);
INSERT INTO station VALUES(176,'원동역',68);
INSERT INTO station VALUES(177,' 물금역',68);
INSERT INTO station VALUES(178,'군북역',69);
INSERT INTO station VALUES(179,'함안역',69);
INSERT INTO station VALUES(180,'강구역',70);
INSERT INTO station VALUES(181,'장사역',70);
INSERT INTO station VALUES(182,'영덕역',70);
INSERT INTO station VALUES(183,'구미역',71);
INSERT INTO station VALUES(184,'사곡역',71);
INSERT INTO station VALUES(185,'개포역',72);
INSERT INTO station VALUES(186,'예천역',72);
INSERT INTO station VALUES(187,'용궁역',72);
INSERT INTO station VALUES(188,'건천역',73);
INSERT INTO station VALUES(189,'경주역',73);
INSERT INTO station VALUES(190,'불국사역',73);
INSERT INTO station VALUES(191,'서경주역',73);
INSERT INTO station VALUES(192,'신경주역',73);
INSERT INTO station VALUES(193,'안강역',73);
INSERT INTO station VALUES(194,'경산역',74);
INSERT INTO station VALUES(195,'하양역',74);
INSERT INTO station VALUES(196,'남성현역',75);
INSERT INTO station VALUES(197,'청도역',75);
INSERT INTO station VALUES(198,'봉화역',76);
INSERT INTO station VALUES(199,'분천역',76);
INSERT INTO station VALUES(200,'현동역',76);
INSERT INTO station VALUES(201,'춘향역',76);
INSERT INTO station VALUES(202,'석포역',76);
INSERT INTO station VALUES(203,'승부역',76);
INSERT INTO station VALUES(204,'양원역',76);
INSERT INTO station VALUES(205,'임기역',76);
INSERT INTO station VALUES(206,'북영천역',77);
INSERT INTO station VALUES(207,'신녕역',77);
INSERT INTO station VALUES(208,'영천역',77);
INSERT INTO station VALUES(209,'함창역',78);
INSERT INTO station VALUES(210,'청리역',78);
INSERT INTO station VALUES(211,'상주역',78);
INSERT INTO station VALUES(212,'옥산역',78);
INSERT INTO station VALUES(213,'화본역',79);
INSERT INTO station VALUES(214,'휘방사역',80);
INSERT INTO station VALUES(215,'풍기역',80);
INSERT INTO station VALUES(216,'영주역',80);
INSERT INTO station VALUES(217,'포항역',81);
INSERT INTO station VALUES(218,'월포역',81);
INSERT INTO station VALUES(219,'탑리역',82);
INSERT INTO station VALUES(220,'의성역',82);
INSERT INTO station VALUES(221,'점촌역',83);
INSERT INTO station VALUES(222,'신동역',84);
INSERT INTO station VALUES(223,'약목역',84);
INSERT INTO station VALUES(224,'왜관역',84);
INSERT INTO station VALUES(225,'안동역',85);
INSERT INTO station VALUES(226,'김천역',86);
INSERT INTO station VALUES(227,'김천구미',86);
INSERT INTO station VALUES(228,'인천공항t1',87);
INSERT INTO station VALUES(229,'인천공항t2',87);
INSERT INTO station VALUES(230,'대전역',88);
INSERT INTO station VALUES(231,'신탄진역',88);
INSERT INTO station VALUES(232,'서대전역',88);
INSERT INTO station VALUES(233,'대구역',89);
INSERT INTO station VALUES(234,'동대구역',89);
INSERT INTO station VALUES(235,'구포역',90);
INSERT INTO station VALUES(236,'부산역',90);
INSERT INTO station VALUES(237,'기장역',90);
INSERT INTO station VALUES(238,'부전역',90);
INSERT INTO station VALUES(239,'화명역',90);
INSERT INTO station VALUES(240,'좌천역',90);
INSERT INTO station VALUES(241,'사상역',90);
INSERT INTO station VALUES(242,'센텀역',90);
INSERT INTO station VALUES(243,'신해운대역',90);
INSERT INTO station VALUES(244,'남창역',91);
INSERT INTO station VALUES(245,'덕하역',91);
INSERT INTO station VALUES(246,'호계역',91);
INSERT INTO station VALUES(247,'태화강',91);
INSERT INTO station VALUES(248,'울산역',91);
INSERT INTO station VALUES(249,'광주역',92);
INSERT INTO station VALUES(250,'광주송정역',92);
INSERT INTO station VALUES(251,'극락강역',92);
INSERT INTO station VALUES(252,'효천역',92);
INSERT INTO station VALUES(253,'서광주역',92);

INSERT INTO place VALUES(1,'청평면 고성리 616-2','여행 > 관광,명소',127.49072076943015, 37.71502775032536, '쁘띠프랑스', '031-584-8200', 'http://place.map.kakao.com/7920064', 1, 1);
INSERT INTO place VALUES(2,'경기 가평군 상면 행현리 623-3','여행 > 관광,명소 > 수목원,식물원',127.35166124525132, 37.74300402014755, '아침고요수목원', '1544-6703', 'http://place.map.kakao.com/25855305', 1, 1);
INSERT INTO place VALUES(3,'경기 가평군 가평읍 달전리 30','여행 > 관광,명소 > 섬 > 섬(내륙)',127.52794671299, 37.8157523632236, '자라섬', '', 'http://place.map.kakao.com/8059024', 1, 1);
INSERT INTO place VALUES(4,'경기 가평군 가평읍 읍내리 395-1','여행 > 관광,명소 > 테마파크',127.515864051987, 37.8289525253873, '가평레일파크', '031-582-7788', 'http://place.map.kakao.com/27092396', 1, 1);
INSERT INTO place VALUES(5,'경기 가평군 설악면 이천리 304-31','여행 > 관광,명소 > 테마파크',127.4474798697605, 37.66778896494794, '에델바이스 스위스 테마파크', '031-585-3359', 'http://place.map.kakao.com/27092396', 1, 1);

INSERT INTO vlog VALUES(1,'제목1','CKvzYfkgTyc');
INSERT INTO vlog VALUES(2,'제목2','uugSc5MwlSE');
INSERT INTO vlog VALUES(3,'제목3','4MbZC95AKVk');

INSERT INTO place_vlog VALUES(1,1,1);
INSERT INTO place_vlog VALUES(2,2,1);
INSERT INTO place_vlog VALUES(3,4,1);
INSERT INTO place_vlog VALUES(4,2,2);
INSERT INTO place_vlog VALUES(5,4,2);
INSERT INTO place_vlog VALUES(6,5,2);
INSERT INTO place_vlog VALUES(7,1,3);
INSERT INTO place_vlog VALUES(8,3,3);
INSERT INTO place_vlog VALUES(9,5,3);
INSERT INTO place_vlog VALUES(10,2,3);
#
# INSERT INTO member VALUES(1,'주리링1','1234');
# INSERT INTO member VALUES(2,'주리링2','1234');
# INSERT INTO member VALUES(3,'주리링3','1234');
# INSERT INTO member VALUES(4,'주리링4','1234');
# INSERT INTO member VALUES(5,'주리링5','1234');

#
# INSERT INTO myplace VALUES(1,'주소',1,123.12,36.16,'순천만습지1',1);
#
# INSERT INTO myplace VALUES(2,'주소',1,123.12,36.16,'순천만습지2',1);
#
# INSERT INTO myplace VALUES(3,'주소',1,123.12,36.16,'순천만습지3',1);
#
# INSERT INTO myplace VALUES(4,'주소',1,123.12,36.16,'순천만습지4',1);
#
# INSERT INTO myplace VALUES(5,'주소',1,123.12,36.16,'순천만습지5',1);
#
# INSERT INTO myplace VALUES(6,'주소',1,123.12,36.16,'순천만습지6',1);
#
# INSERT INTO myplace VALUES(7,'주소',1,123.12,36.16,'순천만습지7',1);
#
# INSERT INTO myplace VALUES(8,'주소',1,123.12,36.16,'순천만습지8',1);
#
# INSERT INTO myplace VALUES(9,'주소',1,123.12,36.16,'순천만습지9',1);
#
# INSERT INTO myplace VALUES(10,'주소',1,123.12,36.16,'순천만습지10',1);